# Site settings
title: void chiyaStudio()
SEOTitle: 千夜ch1y4's Studio
header-img: img/main/desk.jpg
email: null@null.null
description: "Nothing is possible."
keyword: "千夜ch1y4, 千夜chiya, 网络, 运维, 安全, 单片机, ARM, FPGA, DSP, Linux"
url: "http://panzhifei.fun"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/ch1y4/ch1y4.github.io.git" # you code repository

# Publish posts or collection documents with a future date.
future: true

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Nothing is possible."
sidebar-avatar: /img/main/chiya.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
#weibo_username:     
zhihu_username:     takanashi_tsubasa
github_username:    ch1y4
#facebook_username:  
#bilibili_username:   
twitter_username:   chiya_ch1y4




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead。
highlighter: rouge
permalink: pretty
paginate: 100
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
#gems: [jekyll-paginate]
# for Jekyll 4 ,use this
plugins: [jekyll-paginate]
#plugins: [jekyll-target-blank]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: 

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID:      #生成的clientID
  clientSecret:    #生成的clientSecret
  repo:     #仓库名称
  owner:    #github用户名
  admin: 
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: 

# Google Analytics
#ga_track_id: 'UA-175676693-1'            # Format: UA-xxxxxx-xx
#ga_domain: panzhifei.fun                # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 5              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true



# Friends
friends: [
    {
        title: "稚晖的个人站",
        href: "http://www.pengzhihui.xyz/"
    },{
        title: "IAMLIUBO",
        href: "https://blogs.oopswow.com/"
    },{
        title: "Hello from Junde Yhi",
        href: "https://www.yhi.moe/"
    },{
        title: "好奇吖斌",
        href: "http://www.haoqiabin.cn/"
    },{
        title: "IT1995",
        href: "http://www.it1995.cn/"
    },{
        title: "module ZephRay;",
        href: "https://zephray.me/"
    },{
        title: "谷治眠's code World",
        href: "http://www.guzhimian.fun/"
    }
]
